### PR TITLE
WIP: port to Rust

### PR DESCRIPTION
**Pull request by bbigras**
Here's a quick version.

It might be overkill to use anyhow, dialoguer and structopt but it was quicker.

I was thinking it could be better, instead of calling Process many times to do something like `vread(&secret).then(|stdout| ...)` to simplify the code. but I'm thinking it would be better to just use the vault API (by using a Rust crate or directly).

Oh I forgot to strip the newline for the QR core.

EDITI: haha I also forgot to rename the `no cmd.stdout?` messages.

Don't be shy to criticize it.

### CODE REVIEW

**Comment by bbigras** [comment]
A rust crate could be used for the QR code too. Maybe `genpass` should be kept since it's probably better than some random rust crate.

**Comment by bbigras** [comment]
Did you try https://github.com/sethvargo/vault-secrets-gen ? I wonder if it could replace genpass.

**Comment by cole-h** [comment]
I used the `qrcode` crate in my `passrs` project. For inspiration, you can see how I did the QR printing [here](https://github.com/cole-h/passrs/blob/edd91b51ebee9915a9f72c9ff102041a7a7f35db/src/subcmds/otp/uri.rs) ("interesting" stuff starts at line 29, and the actual "generate the QR code to print" happens in the function at line 99).

**Comment by bbigras** [comment]
> I used the `qrcode` crate in my `passrs` project. For inspiration, you can see how I did the QR printing [here](https://github.com/cole-h/passrs/blob/edd91b51ebee9915a9f72c9ff102041a7a7f35db/src/subcmds/otp/uri.rs) ("interesting" stuff starts at line 29, and the actual "generate the QR code to print" happens in the function at line 99).

Thanks. About `for otp in lines {`, you treat each line a 1 password and print a qr code for everyone of them?

I pushed changes to use the `qrcode` crate and "Improve" the error messages.

I don't trim the newline for the qrcode yet. i want to make sure what pass' behavior is first.

**Comment by cole-h** [comment]
The `for otp in lines {` is just checking every line of a file for a valid OTP secret string (exact format I have documented somewhere... probably near the `validate::validate()` function). Once it finds one, then it will transform the OTP string into the QrCode struct to operate on (get the QR grid):

https://github.com/cole-h/passrs/blob/edd91b51ebee9915a9f72c9ff102041a7a7f35db/src/subcmds/otp/uri.rs#L29-L39

This is because not everybody has their OTP in the `username/otp` file -- some just add it to wherever they have their password stored.

**Comment by bbigras** [comment]
@cole-h thanks.

@grahamc do you want to review the PR as is? I wonder what happens if a QR code contains a newline.

I'm thinking maybe we could merge this basic version, and then I could make another PR to switch to the vault's API.

**Pull request closed without merging**
